apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: deployment.yaml
  - path: service.yaml

replicas:
  - count: 7
    name: vote

namespace: instavote

images:
  - name: schoolofdevops/vote
    newTag: v4

commonAnnotations:
  supported-by: ulrich.kemp@telekom.de

configMapGenerator:
- envs:
  - options.env
  name: vote-options

labels:
- includeSelectors: true
  pairs:
    env: staging
    project: instavote
